#!/bin/bash

set -eu 
export LANG=C

SCRIPT_DIR=$(cd $(dirname $0);pwd)

HOST_NAME=${1:?err}
OPT=${2:=""}

#温度
showTempeature (){
  ./yamahashow $1 environment | grep "^Inside Temperature(C.):"   | awk '{print $3}'
}
#showTempeature ${HOST_NAME}


#CPU Usage
showCPUUsage (){
#CPU:  11%(5sec)  17%(1min)  17%(5min) 
  ./yamahashow $1 environment | grep "^CPU:" | awk '{print $2}'  | sed -e "s/^\([0-9]\{1,3\}\)%(.*)$/\1/g" 
}
#showCPUUsage ${HOST_NAME}

#メモリ使用率
showMemoryUsage (){
#CPU:  11%(5sec)  17%(1min)  17%(5min) 
  ./yamahashow $1 environment | grep -E "^CPU.*Memory:" | awk '{print $6}' | sed -e "s/%$//g"
}
#showMemoryUsage ${HOST_NAME}

#sh wlx302.sh 192.168.100.5 SSID_NAME 
showSsid (){
  ./yamahashow $1 "status airlink module"  | grep "ESSID:\"$2\"" -A8 -B1
}
showSsid ${HOST_NAME} $OPT

#Wifi 同時接続数 SSID毎

